### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by sumin12345678** [yangliu9527/Object_SLAM#3]
Firstly, thank you for your excellent work. I would like to know how datasets are processed and if there are any tutorials or Python code available. Looking forward to your reply. Thanks

**Comment by yangliu9527** [comment]
I used [YOLACT](https://github.com/dbolya/yolact) to acquire the instance segmentation results of original images. I‘m sorry that the script I used is missing. But I can give you some suggestions based on the source code of [YOLACT](https://github.com/dbolya/yolact).  The eval.py in its repository is the main code to extract semantic results but it only outputs a visible result instead of detailed data of masks, bounding boxes. So you have to modify eval.py by yourself to get what you want. You can access to the raw results from predispaly(), and you need to modify evalimage(), evalimages() to store results. 

By the way, nowadays there are more reliable instance segmentation methods you can try.

**Comment by sumin12345678** [comment]
When I used YOLOV8S SEG pre trained model for segmentation, I found that there were not as many objects detected in the same image as YOLACT, but that may be related to model training.
Thank you for your prompt and detailed answer. Wishing you a happy life!
